FROM ruby:2.5-alpine

RUN apk add --update --virtual build-dependencies \
      make \
      gcc \
      g++ \
      python \
      git \
      npm \
 && apk add --update --no-cache \
      nodejs \
 && npm config set loglevel error \
 && npm install dredd \
 && gem install dredd_hooks \
 && apk del --purge build-dependencies

ENV PATH ${PATH}:/node_modules/.bin
