swagger: '2.0'
info:
  version: 0.1.0
  title: Toolbox
host: 'localhost:5000'
basePath: /
tags:
  - name: dependency
    description: Everything about Dependencies
  - name: comment
    description: Access to Dependencies Comments
schemes:
  - http
paths:
  '/dependencies/{dependencies_id}':
    get:
      tags:
        - dependency
      summary: Find dependency by ID
      description: Returns a single dependency
      operationId: getDependencyById
      produces:
        - application/json
      parameters:
        - name: dependencies_id
          in: path
          description: ID of dependency to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Dependency'
        '404':
          description: Dependency not found
definitions:
  Dependency:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: Rubocop
      comments:
        type: array
        items:
          $ref: '#/definitions/Comment'
  Comment:
    type: object
    required:
      - body
    properties:
      id:
        type: integer
        format: int64
      body:
        type: string
        example: Hello world !
      published:
        type: boolean
        example: true
